language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
    allow_failure:
        - php: 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: bin/phpspec run -fpretty --verbose

notifications:
    email:  "zoja87@gmail.com"
